services:
  - type: web
    name: dbms-project
    env: node
    buildCommand: bash ./render-native-build.sh
    startCommand: node server.js
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_CONNECTSTRING
        sync: false
      - key: INSTANT_CLIENT_PATH
        value: /opt/render/project/src/.render/oracle/instantclient_23_8
      - key: NODE_ENV
        value: production
