services:
  - type: web
    name: dbms-project
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_CONNECTSTRING
        sync: false
      - key: ORACLE_DRIVER_MODE
        value: thick
      - key: NODE_ENV
        value: production
